# Generated by Django 3.0.6 on 2020-06-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_seed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_complete',
        ),
    ]
