# Generated by Django 3.0.6 on 2021-01-23 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0002_auto_20200604_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFunzionaleCoinvolta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, unique=True, verbose_name='CTU-Area funzionale coinvolta')),
            ],
            options={
                'verbose_name': 'CTU - Area funzionale',
                'verbose_name_plural': 'CTU- Aree funzionali',
            },
        ),
        migrations.CreateModel(
            name='ProfiloOperatoreCoinvolto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilo', models.CharField(max_length=100, unique=True, verbose_name='CTU - Profilo operatore coinvolto')),
            ],
            options={
                'verbose_name': 'CTU-Profilo operatore',
                'verbose_name_plural': 'CTU-Profili operatori',
            },
        ),
        migrations.CreateModel(
            name='TipologiaErrore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=100, unique=True, verbose_name='CTU - Tipologia di errore')),
            ],
            options={
                'verbose_name': 'CTU-Tipologia di errore',
                'verbose_name_plural': 'CTU-Tipologie di errori',
            },
        ),
        migrations.CreateModel(
            name='Ctu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_nativo_digitale', models.BooleanField(default=False, help_text='Tick su casella se sì', verbose_name='File nativo digitale')),
                ('tipo_procedimento', models.SmallIntegerField(choices=[(0, 'Accertamento tecnico preventivo ai sensi art. 696 bis'), (1, 'Consulenza tecnica preventiva'), (2, 'Giudizio di merito'), (3, 'Giudizio di appello'), (4, 'Mediazione EX D. LGS. 28/2010')], verbose_name='Tipologia di procedimento')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('qualifica_ctu', models.TextField(blank=True, default='', verbose_name='Qualifica CTU')),
                ('quesito_formulato', models.TextField(blank=True, default='', verbose_name='Quesito formulato')),
                ('consulenza_med_legale_parte_ric', models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Consulenza medico legale di parte ricorrente')),
                ('errore_lamentato', models.TextField(blank=True, default='', help_text="Se non c'è consulenza medico legale parte ricorrente, lasciare in bianco.", verbose_name='Errore lamentato')),
                ('richiesta_danni', models.TextField(blank=True, default='', verbose_name='RIchiesta danni')),
                ('consulenza_med_legale_parte_con', models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Consulenza medico legale di parte convenuta')),
                ('considerazioni_difensive', models.TextField(blank=True, default='', help_text="Se non c'è consulenza medico legale parte convenuta, lasciare in bianco.", verbose_name='Considerazioni difensive')),
                ('proposta_risarcitoria', models.TextField(blank=True, default='', verbose_name='Proposta risarcitoria')),
                ('infortunato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odp_app.Infortunato', verbose_name='Danneggiato')),
            ],
            options={
                'verbose_name': 'Scheda CTU',
                'verbose_name_plural': 'Schede CTU',
            },
        ),
    ]
