# Generated by Django 3.0.6 on 2021-01-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0003_areafunzionalecoinvolta_ctu_profilooperatorecoinvolto_tipologiaerrore'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='area_funzionale_coinvolta_princ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schede_ctu_princ_set', to='odp_app.AreaFunzionaleCoinvolta', verbose_name='Principale area funzionale coinvolta'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='area_funzionale_coinvolta_sec',
            field=models.ManyToManyField(blank=True, related_name='schede_ctu_sec_set', to='odp_app.AreaFunzionaleCoinvolta', verbose_name='Aree funzionali coinvolte secondarie'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='citazioni_bibliografice',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Citazioni bibliografiche'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='corresponsabilita_altri',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Corresponsabilità di altri enti/aziende'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='identificazione_responsabilita',
            field=models.SmallIntegerField(choices=[(0, 'Presente'), (1, 'Assente'), (2, 'Dubbia')], default=2, verbose_name='Identificazione responsabilità'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctu',
            name='identificazione_responsabilita_arg',
            field=models.TextField(blank=True, default='', help_text="Se non c'è identificazione responsabilità, lasciare in bianco.", verbose_name='Argomentazione su identificazione responsabilità'),
        ),
    ]
