# Generated by Django 3.0.6 on 2021-01-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0004_auto_20210124_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='profilo_operatore_coinvolto_princ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schede_ctu_princ_set', to='odp_app.ProfiloOperatoreCoinvolto', verbose_name='Profilo del principale operatore coinvolto'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='profilo_operatore_coinvolto_sec',
            field=models.ManyToManyField(blank=True, related_name='schede_ctu_sec_set', to='odp_app.ProfiloOperatoreCoinvolto', verbose_name='Profili secondari operatori coinvolti'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='tipologia_errore',
            field=models.ManyToManyField(null=True, to='odp_app.TipologiaErrore', verbose_name='Tipologia/e di errore/i'),
        ),
    ]
