# Generated by Django 3.0.6 on 2021-01-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0005_auto_20210124_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='tipologia_errore',
            field=models.ManyToManyField(to='odp_app.TipologiaErrore', verbose_name='Tipologia/e di errore/i'),
        ),
    ]
