# Generated by Django 3.0.6 on 2021-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0006_auto_20210124_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='danno_biologico_permanente',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Danno biologico permanente'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_biologico_terminale',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Danno biologico terminale'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_differenziale_inail',
            field=models.TextField(blank=True, default='', verbose_name='Argomentazione su identificazione responsabilità'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_iatrogeno_differenziale_dal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Danno iatrogeno differenziale - Al...'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_jure_proprio',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Danno jure proprio'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_morte',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Danno da morte'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='percentuale_danno_permanente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Percentuale del danno biologico permanente'),
        ),
    ]
