# Generated by Django 3.0.6 on 2021-01-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0007_auto_20210124_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='danno_perdita_chances_di_sopravvivenza',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lasciare libero se non sussiste il danno.', max_digits=5, null=True, verbose_name='Danno da perdita chances di sopravvivenza (%)'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_perdita_chances_guarigione',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Danno causato da perdita di chances di guarigione'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='danno_perdita_chances_guarigione_arg',
            field=models.TextField(blank=True, default='', help_text="Se non c'è danno, lasciare in bianco.", verbose_name='Indicazioni sul danno da perdita di chances di guarigione'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='ctu/', verbose_name='Allega un pdf'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note (opzionale)'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='riduzione_capacita_lavorativa_specifica',
            field=models.SmallIntegerField(choices=[(0, 'Si'), (1, 'No'), (2, 'Non applicabile')], default=0, verbose_name='Riduzione capacità lavorativa specifica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctu',
            name='riduzione_capacita_lavorativa_specifica_arg',
            field=models.TextField(blank=True, default='', verbose_name='Dettagli sulla riduzione di capacità lavorativa specifica'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='riferimento_valutativo',
            field=models.SmallIntegerField(choices=[(0, 'Altro (specificare)'), (1, 'Tabella Comm. Min. ex DM 26/5/2004'), (2, 'Linee guida SIMLA 2016'), (3, 'Ronchi et al, 2015'), (4, 'Tabelle DM 3/7/03')], default=3, verbose_name='Riferimento valutativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctu',
            name='rimborso_spese_mediche_prodotte',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Rimborso spese mediche prodotte'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='rimborso_spese_mediche_prodotte_arg',
            field=models.TextField(blank=True, default='', verbose_name='Dettagli sul rimborso delle spese mediche prodotte'),
        ),
        migrations.AlterField(
            model_name='ctu',
            name='identificazione_responsabilita_arg',
            field=models.TextField(blank=True, default='', help_text='Specificare se necessario, altrimenti si può lasciare in bianco.', verbose_name='Riferimento valutativo'),
        ),
    ]
