# Generated by Django 3.0.6 on 2021-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0008_auto_20210124_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='danno_iatrogeno_differenziale_al',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Danno iatrogeno differenziale - Al...'),
        ),
        migrations.AlterField(
            model_name='ctu',
            name='danno_iatrogeno_differenziale_dal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Danno iatrogeno differenziale - Dal...'),
        ),
        migrations.AlterField(
            model_name='ctu',
            name='danno_perdita_chances_guarigione',
            field=models.BooleanField(default=False, help_text='Check se si, lasciare bianco se no', verbose_name='Danno da perdita di chances di guarigione'),
        ),
    ]
