# Generated by Django 3.0.6 on 2021-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0010_ctu_accoglimento_giudice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='accoglimento_giudice',
            field=models.SmallIntegerField(choices=[(0, 'Non applicabile'), (1, 'Parziale'), (2, 'Totale'), (3, 'Negato'), (4, 'Ordinanza')], verbose_name='Accoglimento giudice'),
        ),
    ]
