# Generated by Django 3.0.6 on 2021-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0011_auto_20210211_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='riferimento_valutativo_arg',
            field=models.TextField(blank=True, default='', help_text='Specificare se necessario, altrimenti si può lasciare in bianco.', verbose_name='Riferimento valutativo'),
        ),
        migrations.AlterField(
            model_name='ctu',
            name='identificazione_responsabilita_arg',
            field=models.TextField(blank=True, default='', help_text="Se non c'è identificazione responsabilità, lasciare in bianco.", verbose_name='Argomentazione su identificazione responsabilità'),
        ),
    ]
