# Generated by Django 3.0.6 on 2021-03-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0013_auto_20210211_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctu',
            name='infortunato',
        ),
        migrations.AddField(
            model_name='ctu',
            name='sentenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='odp_app.Sentenza', verbose_name='Sentenza'),
        ),
        migrations.AddField(
            model_name='ctu',
            name='esaminatore',
            field=models.ManyToManyField(to='odp_app.Esaminatore', verbose_name='esaminatore'),
        ),
    ]
