# Generated by Django 3.0.6 on 2021-03-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0013_auto_20210211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='infortunato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='odp_app.Infortunato', verbose_name='Danneggiato'),
        ),
    ]
