# Generated by Django 3.0.6 on 2021-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0015_auto_20210302_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctu',
            name='esaminatore',
            field=models.ManyToManyField(to='odp_app.Esaminatore', verbose_name='esaminatore'),
        ),
    ]
