# Generated by Django 3.0.6 on 2021-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odp_app', '0017_auto_20210302_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='esaminatore',
            field=models.ManyToManyField(to='odp_app.Esaminatore', verbose_name='esaminatore'),
        ),
    ]
